# Generated by Django 5.1.2 on 2024-11-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('department', models.CharField(blank=True, choices=[('HR', 'HR'), ('ENGINEERING', 'Engineering'), ('SALES', 'Sales')], max_length=32)),
                ('role', models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('DEVELOPER', 'Developer'), ('ANALYST', 'Analyst')], max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
