# Generated by Django 5.1.2 on 2024-11-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
