# Generated by Django 5.1.2 on 2024-11-03 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_mgmt', '0002_employee_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+(\\s[a-zA-Z]+){0,2}$', 'Only english alphabets are allowed with names separated by spaces')]),
        ),
    ]
